// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UKW_sklep.czw.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20250306081459_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UKW_sklep.czw.Models.Category", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Category"));

                    b.Property<int>("Desc")
                        .HasColumnType("int");

                    b.Property<int>("Id_Id_Film")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id_Category");

                    b.ToTable("CAtegoryContext");
                });

            modelBuilder.Entity("UKW_sklep.czw.Models.Film", b =>
                {
                    b.Property<int>("Id_Film")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Film"));

                    b.Property<int>("Desc")
                        .HasColumnType("int");

                    b.Property<int>("Director")
                        .HasMaxLength(600)
                        .HasColumnType("int");

                    b.Property<int>("Id_Id_Catefory")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Film");

                    b.ToTable("FilmContex");
                });
#pragma warning restore 612, 618
        }
    }
}
