// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UKW_sklep.czw.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UKW_sklep.czw.Models.Category", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Category"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Id_Film")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Category");

                    b.ToTable("CategoryContext");

                    b.HasData(
                        new
                        {
                            Id_Category = 1,
                            Desc = "High-paced movies with lots of physical activity and stunts.",
                            Name = "Action"
                        },
                        new
                        {
                            Id_Category = 2,
                            Desc = "Movies designed to make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id_Category = 3,
                            Desc = "Movies with a focus on realistic storytelling and emotional themes.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id_Category = 4,
                            Desc = "Movies intended to scare or unsettle the audience.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id_Category = 5,
                            Desc = "Science fiction movies that often involve futuristic technology and space exploration.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id_Category = 6,
                            Desc = "Movies that focus on romantic relationships.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id_Category = 7,
                            Desc = "Movies that are suspenseful and keep the audience on the edge of their seats.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id_Category = 8,
                            Desc = "Movies that include magical or supernatural elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id_Category = 9,
                            Desc = "Movies that provide a factual representation of real events.",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id_Category = 10,
                            Desc = "Movies that use animated images to tell a story.",
                            Name = "Animation"
                        });
                });

            modelBuilder.Entity("UKW_sklep.czw.Models.Film", b =>
                {
                    b.Property<int>("Id_Film")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Film"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("Id_Id_Category")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Film");

                    b.ToTable("FilmContex");

                    b.HasData(
                        new
                        {
                            Id_Film = 1,
                            Desc = "A mind-bending thriller about dreams within dreams.",
                            Director = "Christopher Nolan",
                            Title = "Inception"
                        },
                        new
                        {
                            Id_Film = 2,
                            Desc = "A powerful crime drama about an Italian-American mafia family.",
                            Director = "Francis Ford Coppola",
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id_Film = 3,
                            Desc = "A gripping superhero film featuring Batman's battle against the Joker.",
                            Director = "Christopher Nolan",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id_Film = 4,
                            Desc = "A nonlinear narrative that interweaves various crime stories.",
                            Director = "Quentin Tarantino",
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id_Film = 5,
                            Desc = "A poignant historical drama about the Holocaust.",
                            Director = "Steven Spielberg",
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id_Film = 6,
                            Desc = "A revolutionary sci-fi film about a dystopian future and virtual reality.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id_Film = 7,
                            Desc = "A psychological drama exploring identity and consumer culture.",
                            Director = "David Fincher",
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id_Film = 8,
                            Desc = "A heartwarming tale of an unlikely hero's journey through life.",
                            Director = "Robert Zemeckis",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id_Film = 9,
                            Desc = "A story of hope and friendship within the walls of a prison.",
                            Director = "Frank Darabont",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id_Film = 10,
                            Desc = "The epic adventure of a hobbit and his quest to destroy a powerful ring.",
                            Director = "Peter Jackson",
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id_Film = 11,
                            Desc = "The beginning of an epic space saga.",
                            Director = "George Lucas",
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id_Film = 12,
                            Desc = "A story of revenge and redemption in ancient Rome.",
                            Director = "Ridley Scott",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id_Film = 13,
                            Desc = "A chilling thriller featuring a brilliant but deranged serial killer.",
                            Director = "Jonathan Demme",
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id_Film = 14,
                            Desc = "A sci-fi adventure about a theme park with genetically engineered dinosaurs.",
                            Director = "Steven Spielberg",
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id_Film = 15,
                            Desc = "An animated classic about a lion cub's journey to adulthood and kingship.",
                            Director = "Roger Allers, Rob Minkoff",
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id_Film = 16,
                            Desc = "A romantic drama set against the backdrop of the ill-fated Titanic voyage.",
                            Director = "James Cameron",
                            Title = "Titanic"
                        },
                        new
                        {
                            Id_Film = 17,
                            Desc = "A visually stunning sci-fi epic set on the alien world of Pandora.",
                            Director = "James Cameron",
                            Title = "Avatar"
                        },
                        new
                        {
                            Id_Film = 18,
                            Desc = "A harrowing World War II drama about a mission to save a soldier.",
                            Director = "Steven Spielberg",
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id_Film = 19,
                            Desc = "A sci-fi epic exploring space travel and the quest to save humanity.",
                            Director = "Christopher Nolan",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id_Film = 20,
                            Desc = "A supernatural drama set on death row in a Southern prison.",
                            Director = "Frank Darabont",
                            Title = "The Green Mile"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
