// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UKW_sklep.czw.DAL;

#nullable disable

namespace UKW_sklep.czw.Migrations.Films
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250601155314_MigracaPoster")]
    partial class MigracaPoster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UKW_sklep.czw.Models.Category", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Category"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Category");

                    b.ToTable("CategoryContext");

                    b.HasData(
                        new
                        {
                            Id_Category = 1,
                            Desc = "High-paced movies with lots of physical activity and stunts.",
                            Name = "Action"
                        },
                        new
                        {
                            Id_Category = 2,
                            Desc = "Movies designed to make the audience laugh.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id_Category = 3,
                            Desc = "Movies with a focus on realistic storytelling and emotional themes.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id_Category = 4,
                            Desc = "Movies intended to scare or unsettle the audience.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id_Category = 5,
                            Desc = "Science fiction movies that often involve futuristic technology and space exploration.",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id_Category = 6,
                            Desc = "Movies that focus on romantic relationships.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id_Category = 7,
                            Desc = "Movies that are suspenseful and keep the audience on the edge of their seats.",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id_Category = 8,
                            Desc = "Movies that include magical or supernatural elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id_Category = 9,
                            Desc = "Movies that provide a factual representation of real events.",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id_Category = 10,
                            Desc = "Movies that use animated images to tell a story.",
                            Name = "Animation"
                        });
                });

            modelBuilder.Entity("UKW_sklep.czw.Models.Film", b =>
                {
                    b.Property<int>("Id_Film")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Film"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Film");

                    b.HasIndex("CategoryId");

                    b.ToTable("FilmContex");

                    b.HasData(
                        new
                        {
                            Id_Film = 1,
                            CategoryId = 5,
                            Desc = "A mind-bending thriller about dreams within dreams.",
                            Director = "Christopher Nolan",
                            Poster = "Inception.png",
                            Price = 24.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            Id_Film = 2,
                            CategoryId = 3,
                            Desc = "A powerful crime drama about an Italian-American mafia family.",
                            Director = "Francis Ford Coppola",
                            Poster = "The_God_father.png",
                            Price = 19.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id_Film = 3,
                            CategoryId = 1,
                            Desc = "A gripping superhero film featuring Batman's battle against the Joker.",
                            Director = "Christopher Nolan",
                            Poster = "The_Dark_Knight.png",
                            Price = 22.49m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id_Film = 4,
                            CategoryId = 3,
                            Desc = "A nonlinear narrative that interweaves various crime stories.",
                            Director = "Quentin Tarantino",
                            Poster = "Pulp_Fiction.png",
                            Price = 17.99m,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id_Film = 5,
                            CategoryId = 9,
                            Desc = "A poignant historical drama about the Holocaust.",
                            Director = "Steven Spielberg",
                            Poster = "Schindlers_List.png",
                            Price = 21.99m,
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id_Film = 6,
                            CategoryId = 5,
                            Desc = "A revolutionary sci-fi film about a dystopian future and virtual reality.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Poster = "The_Matrix.png",
                            Price = 26.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id_Film = 7,
                            CategoryId = 3,
                            Desc = "A psychological drama exploring identity and consumer culture.",
                            Director = "David Fincher",
                            Poster = "Fight_Club.png",
                            Price = 18.49m,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id_Film = 8,
                            CategoryId = 3,
                            Desc = "A heartwarming tale of an unlikely hero's journey through life.",
                            Director = "Robert Zemeckis",
                            Poster = "Forrest_Gump.png",
                            Price = 16.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id_Film = 9,
                            CategoryId = 3,
                            Desc = "A story of hope and friendship within the walls of a prison.",
                            Director = "Frank Darabont",
                            Poster = "The_Shawshank_Redemption.png",
                            Price = 20.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id_Film = 10,
                            CategoryId = 8,
                            Desc = "The epic adventure of a hobbit and his quest to destroy a powerful ring.",
                            Director = "Peter Jackson",
                            Poster = "The_Lord_of_the_Rings.png",
                            Price = 29.99m,
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id_Film = 11,
                            CategoryId = 5,
                            Desc = "The beginning of an epic space saga.",
                            Director = "George Lucas",
                            Poster = "Star Wars_Episode_IV.png",
                            Price = 27.99m,
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id_Film = 12,
                            CategoryId = 1,
                            Desc = "A story of revenge and redemption in ancient Rome.",
                            Director = "Ridley Scott",
                            Poster = "Gladiator.png",
                            Price = 22.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id_Film = 13,
                            CategoryId = 4,
                            Desc = "A chilling thriller featuring a brilliant but deranged serial killer.",
                            Director = "Jonathan Demme",
                            Poster = "The_Silence_of_the_Lambs.png",
                            Price = 19.99m,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id_Film = 14,
                            CategoryId = 5,
                            Desc = "A sci-fi adventure about a theme park with genetically engineered dinosaurs.",
                            Director = "Steven Spielberg",
                            Poster = "Jurassic_Park.png",
                            Price = 25.49m,
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id_Film = 15,
                            CategoryId = 10,
                            Desc = "An animated classic about a lion cub's journey to adulthood and kingship.",
                            Director = "Roger Allers, Rob Minkoff",
                            Poster = "The_Lion_King.png",
                            Price = 14.99m,
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id_Film = 16,
                            CategoryId = 6,
                            Desc = "A romantic drama set against the backdrop of the ill-fated Titanic voyage.",
                            Director = "James Cameron",
                            Poster = "Titanic.png",
                            Price = 23.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            Id_Film = 17,
                            CategoryId = 5,
                            Desc = "A visually stunning sci-fi epic set on the alien world of Pandora.",
                            Director = "James Cameron",
                            Poster = "Avatar.png",
                            Price = 28.99m,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id_Film = 18,
                            CategoryId = 3,
                            Desc = "A harrowing World War II drama about a mission to save a soldier.",
                            Director = "Steven Spielberg",
                            Poster = "Saving_Private_Ryan.png",
                            Price = 21.49m,
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id_Film = 19,
                            CategoryId = 5,
                            Desc = "A sci-fi epic exploring space travel and the quest to save humanity.",
                            Director = "Christopher Nolan",
                            Poster = "Interstellar.png",
                            Price = 27.49m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id_Film = 20,
                            CategoryId = 3,
                            Desc = "A supernatural drama set on death row in a Southern prison.",
                            Director = "Frank Darabont",
                            Poster = "The_Green_Mile.png",
                            Price = 18.99m,
                            Title = "The Green Mile"
                        });
                });

            modelBuilder.Entity("UKW_sklep.czw.Models.Film", b =>
                {
                    b.HasOne("UKW_sklep.czw.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UKW_sklep.czw.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
